project/expenses/models.py
from project import db


class Expense(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	category = db.Column(db.String(150), nullable=False)
	amount = db.Column(db.Numeric(6, 2))
	month_id = db.Column(db.Integer, db.ForeignKey('month.id'), nullable=False)
	description = db.Column(db.Text())
	short_descr = db.Column(db.String(83), nullable=True)

	def __repr__(self):
		return f"Expense('{self.id}', '{self.amount}')"
	
	def __init__(self, **kwargs):
		super(Expense, self).__init__(**kwargs)
		self.set_short_descr()
	
	def set_short_descr(self):
		if self.description and len(self.description) > 80:
			self.short_descr = self.description[:80] + '...'
		else:
			self.short_descr = None


class Month(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	month = db.Column(db.Integer, nullable=False)
	year = db.Column(db.Integer, nullable=False)
	user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
	expenses = db.relationship(
		'Expense', backref='month_related', lazy=True,
		cascade='all, delete-orphan', order_by=('Expense.category')
	)

	def __repr__(self):
		return f"Month('{self.id}', '{self.month}-{self.year}')"

project/expenses/forms.py
from decimal import ROUND_HALF_EVEN
from flask_wtf import FlaskForm
from wtforms import (
	IntegerField, SelectField, SubmitField, DecimalField, StringField, HiddenField
)
from wtforms.validators import DataRequired, NumberRange
from wtforms.widgets import TextArea
from .utils import MONTHS, CATEGORIES


class AddMonthForm(FlaskForm):
	year = IntegerField('Year', validators=[DataRequired(), NumberRange(min=1900, max=2500)])
	month = SelectField('Month', validators=[DataRequired()], choices=MONTHS, coerce=int)
	submit = SubmitField('Add new')


class ExpeneFormMixin():
	amount = DecimalField(
		'Amount',
		places=2,
		rounding=ROUND_HALF_EVEN,
		validators=[
			DataRequired(), NumberRange(min=0.01, max=999999.99)
		]
	)
	category = SelectField(
		'Category', validators=[DataRequired()], choices=CATEGORIES
	)
	description = StringField('Description', widget=TextArea())


class AddExpenseForm(FlaskForm, ExpeneFormMixin):
	submit_add = SubmitField('Save')


class UpdateExpenseForm(FlaskForm, ExpeneFormMixin):
	submit_update = SubmitField('Save')
	expense_id = HiddenField('Expense ID', id='update-id')

project/expenses/routes.py
from datetime import date
from flask import Blueprint, render_template, redirect, url_for, flash, send_from_directory
from flask_login import current_user, login_required
from project import db
from .models import Month, Expense
from .forms import AddMonthForm, AddExpenseForm, UpdateExpenseForm
from .utils import MONTHS, CATEGORIES, DOWNLOADS_PATH, generate_xlsx, generate_pdf


expenses = Blueprint('expenses', __name__, template_folder='templates')

@expenses.route("/", methods=['GET', 'POST'])
@login_required
def main():
	form = AddMonthForm()
	if form.validate_on_submit():
		month = Month(year=form.year.data, month=form.month.data, user_id=current_user.id)
		db.session.add(month)
		db.session.commit()
		return redirect(url_for('expenses.main'))
	user_months = Month.query.filter_by(
		user_id=current_user.id).order_by(Month.year.desc(), Month.month.asc()
	)
	TODAY = date.today()
	CURRENT_MONTH = TODAY.month
	CURRENT_YEAR = TODAY.year
	MONTH_LIST = [month[1] for month in MONTHS]
	return render_template(
		'main.html', title='Homepage', user_months=user_months, form=form,
		months=MONTH_LIST, cr_month=CURRENT_MONTH, cr_year=CURRENT_YEAR
	)

@expenses.route("/delete_month/<month_id>", methods=['GET'])
@login_required
def delete_month(month_id):
	month = Month.query.filter_by(id=month_id).first_or_404()
	if month.user_id == current_user.id:
		db.session.delete(month)
		db.session.commit()
		flash('Month has been deleted!', 'success')
		return redirect(url_for('expenses.main'))
	else:
		flash("You can't delete month that doesn't belongs to you!", 'danger')
		return redirect(url_for('expenses.main'))

@expenses.route('/month/<month_id>', methods=['GET', 'POST'])
@login_required
def month(month_id):
	month = Month.query.filter_by(id=month_id).first_or_404()
	if month.user_id == current_user.id:
		add_form = AddExpenseForm()
		if add_form.submit_add.data and add_form.validate():
			expense = Expense(
				amount=add_form.amount.data, category=add_form.category.data,
				description=add_form.description.data, month_id=month_id
			)
			db.session.add(expense)
			db.session.commit()
			return redirect(url_for('expenses.month', month_id=month.id))
		update_form = UpdateExpenseForm()
		if update_form.submit_update.data and update_form.validate():
			expense = Expense.query.filter_by(id=update_form.expense_id.data).first()
			expense.amount = update_form.amount.data
			expense.category = update_form.category.data
			expense.description = update_form.description.data
			expense.set_short_descr()
			db.session.commit()
			return redirect(url_for('expenses.month', month_id=month.id))
		ROUTE_CATEGORIES = [el[1] for el in CATEGORIES]
		summary = db.session.query(db.func.sum(Expense.amount)).filter_by(month_id=month_id)
		sums = {key: str(summary.filter_by(category=key).first()[0]) for key in ROUTE_CATEGORIES}
		sums['Total'] = str(summary.first()[0])
		month_title = f'{MONTHS[month.month - 1][1]} {month.year}'
		return render_template(
			'month.html', title='Expenses', month=month, sums=sums,
			add_form=add_form, update_form=update_form, month_title=month_title
		)
	else:
		flash("You can't view a month that doesn't belongs to you!!", 'danger')
		return redirect(url_for('expenses.main'))

@expenses.route("/delete_expense/<expense_id>", methods=['GET'])
@login_required
def delete_expense(expense_id):
	expense = Expense.query.filter_by(id=expense_id).first_or_404()
	month = Month.query.filter_by(id=expense.month_id).first()
	if month.user_id == current_user.id:
		db.session.delete(expense)
		db.session.commit()
		flash('Expense has been deleted!', 'success')
		return redirect(url_for('expenses.month', month_id=month.id))
	else:
		flash("You can't delete expense that doesn't belongs to you!", 'danger')
		return redirect(url_for('expenses.month', month_id=month.id))

@expenses.route("/download_xlsx/<month_id>", methods=['GET'])
@login_required
def download_xlsx(month_id):
	month = Month.query.filter_by(id=month_id).first_or_404()
	if month.user_id == current_user.id:
		generate_xlsx(month)
		file_name = f'{MONTHS[month.month][1]}{month.year}.xlsx'
		return send_from_directory(
			DOWNLOADS_PATH, f'{month.user_id}.xlsx', attachment_filename=file_name, as_attachment=True
		)
	else:
		flash("That month is not yours!", 'danger')
		return redirect(url_for('expenses.main'))

@expenses.route("/download_pdf/<month_id>", methods=['GET'])
@login_required
def download_pdf(month_id):
	month = Month.query.filter_by(id=month_id).first_or_404()
	if month.user_id == current_user.id:
		generate_pdf(month)
		return send_from_directory(
			DOWNLOADS_PATH, f'{month.user_id}.pdf', mimetype='application/pdf'
		)
	else:
		flash("That month is not yours!", 'danger')
		return redirect(url_for('expenses.main'))

project/expenses/templates/form_modal.html
<div class="modal{% if form.errors %} is-active{% endif %}" id="{{ case }}-modal">
	<div class="modal-background"></div>
	<div class="modal-card">
	  <header class="modal-card-head">
      <p class="modal-card-title">{{ case[0]|upper}}{{case[1:] }} expense</p>
      <button class="delete" aria-label="close"></button>
	  </header>
	  <form method="POST" action="{% if case == 'update' %}#{%endif%}">
      {{ form.hidden_tag() }}
      <section class="modal-card-body">
        <div class="field is-grouped is-horizontal is-marginless">
          <p class="control has-icons-left">
            {% if form.amount.errors %}
              {{ form.amount(class="input is-danger", placeholder="Amount", id=case + '-amount') }}
            {% else %}
              {{ form.amount(class="input", placeholder="Amount", id=case + '-amount') }}
            {% endif %}
            <span class="icon is-small is-left">
              <i class="far fa-money-bill-alt"></i>
            </span>
          </p>
          <p class="control is-expanded has-icons-left">
            {% if form.category.errors %}
            <span class="select is-fullwidth is-danger">
            {% else %}
            <span class="select is-fullwidth">
            {% endif %}
              {{ form.category(placeholder="Category", id=case + '-category') }}
            </span>
            <span class="icon is-small is-left">
              <i class="fas fa-file-invoice-dollar"></i>
            </span>
          </p>
        </div>
        <div class="columns is-marginless">
          <div class="column has-text-centered">
            {% for error in form.amount.errors %}
              <p class="help is-danger center-fix">{{ error }}</p>
            {% endfor %}
          </div>
          <div class="column has-text-centered">
            {% for error in form.category.errors %}
              <p class="help is-danger is-marginless">{{ error }}</p>
            {% endfor %}
          </div>
        </div>
        <div class="field is-horizontal">
          <div class="field-body">
            {% if form.description.errors %}
              {{ form.description(
                class="textarea is-danger", placeholder="Description", id=case + '-description'
              ) }}
            {% else %}
              {{ form.description(
                class="textarea", placeholder="Description", id=case + '-description'
              ) }}
            {% endif %}
          </div>
        </div>
      </section>
      <footer class="modal-card-foot">
        {% if case == 'update' %}
          {% for error in form.expense_id.errors %}
            <p class="help is-danger">{{ error }}</p>
          {% endfor %}
          {{ form.submit_update(class="button is-primary") }}
        {% else %}
          {{ form.submit_add(class="button is-primary") }}
        {% endif %}
        <button class="button" type="button">Cancel</button>
      </footer>
	  </form>
	</div>
</div>

project/expenses/templates/main.html
{% extends 'base.html' %}
{% block content %}
<form id="months-content" method="POST" action="">
  {{ form.hidden_tag() }}
  <div class="field is-horizontal">
    <div class="field-body">
      <div>
        {% for error in form.year.errors %}
          <span class="has-text-danger is-pulled-right">{{ error }}</span>
          <br>
        {% endfor %}
      </div>
        <p class="control has-icons-left">
          {% if form.year.errors %}
            {{ form.year(class="input is-danger is-large", placeholder="Year") }}
          {% else %}
            {{ form.year(class="input is-large", placeholder="Year") }}
          {% endif %}
          <span class="icon is-small is-left">
            <i class="far fa-calendar"></i>
          </span>
        </p>
      <div class="has-text-centered is-vcentered">
        <p class="control has-icons-left">
          {% if form.month.errors %}
          <span class="select is-large is-danger">
          {% else %}
            <span class="select is-large">
          {% endif %}
          {{ form.month(placeholder="Month") }}
          </span>
          <span class="icon is-small is-left">
            <i class="far fa-calendar-alt"></i>
          </span>
        </p>
        {% for error in form.month.errors %}
          <span class="has-text-danger">{{ error }}</span>
        {% endfor %}
      </div>
      <p class="control">
        {{ form.submit(class="button is-primary is-large") }}
      </p>
    </div>
  </div>
</form>

<div class="columns is-1 is-multiline" id="months">
  {% for month in user_months %}
    <div class="column is-one-third ">
      {% if month.year < cr_year or month.year == cr_year and month.month < cr_month %}
      <div class="has-background-info rounded">
      {% else %}
      <div class="has-background-primary rounded">
      {% endif %}
        <div class="col-hover" data-href="{{ url_for('expenses.month', month_id=month.id) }}">
          <div class="columns is-gapless">
            <div class="column is-three-quarters has-text-centered month-margin month-text-col">
              <h3 class="is-size-3 has-text-white-ter has-text-weight-semibold">
                {{ months[month.month - 1] }}
              </h3 class="">
              <span class="is-size-5 has-text-white-ter">{{ month.year }}</span>
            </div>
            <div class="column">
              <div class="dropdown month-dropdown">
                <div class="dropdown-trigger">
                  <button class="button is-medium is-light is-outlined">
                    <span class="icon is-small">
                      <i class="fas fa-angle-down"></i
                    </span>
                  </button>
                </div>
                <div class="dropdown-menu">
                  <div class="dropdown-content">
                    <a
                      href="{{ url_for('expenses.download_pdf', month_id=month.id) }}"
                      class="dropdown-item">
                      PDF
                    </a>
                    <a
                      href="{{ url_for('expenses.download_xlsx', month_id=month.id) }}"
                      class="dropdown-item"
                    >
                      XLSX
                    </a>
                    <a
                      href="{{ url_for('expenses.delete_month', month_id=month.id) }}"
                      class="dropdown-item"
                    >
                      Delete
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

{% endblock content %}

project/expenses/templates/month.html
{% extends 'base.html' %}
{% block content %}
<div class="columns" id="expenses-header">
  <div class="column">
    <div id="buttons-left">
      <a href="{{ url_for('expenses.main') }}">
        <div class="tooltip"">
          <span class="icon has-text-info is-medium">
            <i class="fas fa-arrow-left fa-2x"></i>
          </span>
          <span class="tooltip-text">Go back</span>
        </div>
      </a>
      <div class="tooltip" id="add-trigger">
        <span class="icon has-text-success is-medium">
          <i class="fas fa-plus fa-2x"></i>
        </span>
        <span class="tooltip-text">Add new</span>
      </div>
    </div>
  </div>
  <div class="column is-three-fifths">
    <h3 class="has-text-centered is-size-3">{{ month_title }}</h3>
  </div>
  <div class="column">
    <div id="buttons-right">
      <a href="{{ url_for('expenses.download_pdf', month_id=month.id) }}">
        <div class="tooltip">
          <span class="icon has-text-primary is-medium">
            <i class="fas fa-file-pdf fa-2x"></i>
          </span>
          <span class="tooltip-text">Download PDF</span>
        </div>
      </a>
      <a href="{{ url_for('expenses.download_xlsx', month_id=month.id) }}">
        <div class="tooltip">
          <span class="icon has-text-primary is-medium">
            <i class="fas fa-file-excel fa-2x"></i>
          </span>
          <span class="tooltip-text">Download XLSX</span>
        </div>
      </a>
      <div class="tooltip">
        <a href="{{ url_for('expenses.delete_month', month_id=month.id) }}">
          <span class="icon has-text-danger is-medium">
            <i class="fas fa-trash-alt fa-2x"></i>
          </span>
        </a>
        <span class="tooltip-text">Delete month</span>
      </div>
    </div>
  </div>
</div>

<table class="table is-hoverable is-bordered is-fullwidth">
	<thead>
	  <tr>
      <th>Amount</th>
      <th>Category</th>
      <th>Description</th>
      <th>Actions</th>
	  </tr>
  </thead>
  <tbody>
    {% for expense in month.expenses %}
      <tr>
        <td class="expense-col">{{ expense.amount }}</td>
        <td class="expense-col">{{ expense.category }}</td>
        <td class="expense-col is-paddingless">
          <div class="expense-toggle">
            {% if expense.short_descr %}
            <div class="short">
              <span class="icon has-text-grey descr-icon">
                <i class="fas fa-angle-down fa-lg"></i>
              </span>
              {{ expense.short_descr }}
            </div>
            <div class="full hidden">
              <span class="icon has-text-info descr-icon">
                <i class="fas fa-angle-up fa-lg"></i>
              </span>
            {% else %}
            <div class="single">
            {% endif %}
              {{ expense.description }}
            </div>
          </div>
        </td>
        <td class="has-text-centered">
          <span
            class="icon has-text-grey edit-icon"
            data-id="{{ expense.id }}"
            data-amount="{{ expense.amount }}"
            data-category="{{ expense.category }}"
            data-description="{{ expense.description }}"
          >
              <i class="fas fa-pencil-alt"></i>
          </span>
          <a href="{{ url_for('expenses.delete_expense', expense_id=expense.id) }}">
            <span class="icon has-text-grey trash-icon">
              <i class="fas fa-trash-alt"></i>
            </span>
          </a>
        </td>
      </tr>
    {% else %}
      <tr>
        <td colspan="4" class="has-text-centered">You didn't add any expenses yet.</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
<table class="table is-hoverable is-bordered is-fullwidth">
  <thead>
    <tr>
      {% for elem_key in sums.keys() %}
        <th class="one-fourth-table-col">{{ elem_key }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    <tr>
      {% for elem_val in sums.values() %}
        {% if elem_val != 'None' %}
          <td>{{ elem_val }}</td>
        {% else %}
          <td>0</td>
        {% endif %}
      {% endfor %}
    </tr>
  </tbody>
</table>

{% with form = add_form, case = 'add' %}
  {% include 'form_modal.html' %}
{% endwith %}
{% with form = update_form, case = 'update' %}
  {% include 'form_modal.html' %}
{% endwith %}
{% endblock content %}